name: Manual Test
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'enable or disable'
        required: true

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - uses: ./
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          workflow_id: test-workflow.yaml
          action: ${{ github.event.inputs.action }}
