name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          yarn install
          yarn all

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: './reports/coverage/lcov.info'

      - name: Test Disable
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: test-workflow.yaml
          action: disable

      - name: Sleep
        run: sleep 10

      - name: Test Enable
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: test-workflow.yaml
          action: enable
